### ISSUE TITLE
Support array calls

### ISSUE THREAD

**Issue by piuccio** [substack/node-detective#26]
Hello,
interesting project.

It would be nice if the module could detect arrays

```
require(["a", "b"], function () {});
```

```
detective("code above");   //   []
````

Useful information can still be obtained from
```
detective.find("code above");
{
   expressions: [  ' [ 'a', 'b' ] '  ]
}
```

However the expression has to be parsed again to extract the array values.

**Comment by zertosh** [comment]
Late by a few years, but you can do `detective.find("code above", {nodes: true});`, and parse out the array values yourself.
