### ISSUE TITLE
Add a note about requires with more than string literals

### ISSUE THREAD

**Issue by adam-lynch** [substack/node-detective#36]
Is it worth adding a note like https://github.com/substack/browserify-handbook/pull/21 here?

Or is `return an array of all the require() calls with string arguments.` enough? (From the readme)

**Comment by zertosh** [comment]
I've thought about this, and kinda, but I'm not sure it's worth supporting. Consider this case:

```js
var myLib = require(process.env.LIB_DIR + '/my-lib');
```

If you use [envify](https://github.com/hughsk/envify) and `process.env.LIB_DIR === '/project/libs'`, then after the transform, you'd have:

```js
var myLib = require('/project/libs' + '/my-lib');
```

That should be concatenated and returned as the require value. But that would open a giant can of worms.
