### ISSUE TITLE
Pass `sourceType` option through to acorn

### ISSUE THREAD

**Issue by anandthakker** [substack/node-detective#54]
Acorn throws an error when parsing a source that uses ES6 module syntax unless it has the `sourceType: 'module'` option (in addition to `ecmaVersion: 6`).

**Comment by anandthakker** [comment]
Here's where: https://github.com/substack/node-detective/blob/master/index.js#L10

**Comment by zertosh** [comment]
it's fixed in detective@4.1.1

**Comment by detectivesmelkor** [comment]
right, fixed in detective @4.1.1
